--define d_arr_integer_udt="integer_tab_t"
--define d_arr_varchar2_udt="varchar2_tab_t"
--define d_arr_arr_varchar2_udt="varchar2_tab_tab_t"
--define d_arr_clob_udt="clob_tab_t"
--define d_arr_arr_clob_udt="clob_tab_tab_t"
define d_arr_integer_udt="arr_integer_udt"
define d_arr_varchar2_udt="arr_varchar2_udt"
define d_arr_arr_varchar2_udt="arr_arr_varchar2_udt"
define d_arr_clob_udt="arr_clob_udt"
define d_arr_arr_clob_udt="arr_arr_clob_udt"
@@install_app_types.sql
